name: Create Ably App

on: 
  push:
    paths:
      - '.github/workflows/create-infra.yml'
  workflow_dispatch:

jobs:
  create_infra:
    runs-on: ubuntu-latest
    name: Create Infrastructure for FFS
    steps:
      - name: Create Ably App
        id: ablyapp
        uses: ably-labs/ably-control-api-action@v0.1.3
        with:
            account-id: '${{ secrets.ABLY_ACCOUNT_ID }}'
            control-api-key: '${{ secrets.ABLY_CONTROL_API_KEY }}'
            app-name: 'fully-featured-scalable-chat'
            create-key: 'true'
            key-name: 'all-capabilities-1'
            key-capabilities: 'channel-metadata, history, presence, publish, push-admin, push-subscribe, statistics, subscribe'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CLI_CREDENTIALS }}
      - name: Azure CLI script
        uses: azure/CLI@v1.0.6
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az staticwebapp appsettings set --name ffschatapp --setting-names "ABLY_API_KEY=${{ steps.ablyapp.outputs.api-key-key }}"