name: Create Infra

on: 
  push:
    paths:
      - '.github/workflows/create-infra.yml'
  workflow_dispatch:

env:
  FUNCTION_APP_NAME: FFSFunctionsApp
  LOCATION: westeurope
  RESOURCE_GROUP_NAME: FFSChat
  STORAGE_ACCOUNT_NAME: storageaccountffsch90c8

jobs:
  create_infra:
    runs-on: ubuntu-latest
    name: Create Infrastructure for FFS
    steps:
      - name: Create Ably App
        id: ablyapp
        uses: ably-labs/ably-control-api-action@v0.1.4
        with:
            account-id: '${{ secrets.ABLY_ACCOUNT_ID }}'
            control-api-key: '${{ secrets.ABLY_CONTROL_API_KEY }}'
            app-name: 'fully-featured-scalable-chat'
            create-key: 'true'
            key-name: 'all-capabilities-1'
            key-capabilities: 'channel-metadata, history, presence, publish, push-admin, push-subscribe, statistics, subscribe'
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CLI_CREDENTIALS }}
      - name: Create Resource Group
        uses: azure/CLI@v1.0.6
        with:
          inlineScript: |
            az group create \
              --name ${{ env.RESOURCE_GROUP_NAME }} \
              --location ${{ env.LOCATION }} \
      - name: Update SWA AppSettings
        uses: azure/CLI@v1.0.6
        with:
          azcliversion: 2.32.0
          inlineScript: |
            az staticwebapp appsettings set --name ffschatapp --setting-names "ABLY_API_KEY=${{ steps.ablyapp.outputs.api-key-key }}"
      - name: Create Storage Account
        uses: azure/CLI@v1.0.6
        with:
          inlineScript: |
            az storage account create \
              --name ${{ env.STORAGE_ACCOUNT_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --location ${{ env.LOCATION }} \
              --sku Standard_LRS \
              --kind Storage \
      - name: Create Function App
        uses: azure/CLI@v1.0.6
        with:
          inlineScript: |
            az functionapp create \
              --name ${{ env.FUNCTION_APP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --consumption-plan-location ${{ env.LOCATION }} \
              --storage-account ${{ env.STORAGE_ACCOUNT_NAME }} \
              --runtime node \
              --runtime-version 16 \
              --os-type Windows \
              --functions-version 4